### ISSUE TITLE
Is not a Lisp

### ISSUE THREAD

**Issue by dfarquharson** [mattHoyDev/nicheLang#6]
Would be even more awesome if it was a Lisp.

But seriously, this is awesome and you guys should give a talk about it.

**Comment by bengangllipson** [comment]
Closing this issue because Lisp is for nerds

**Comment by dfarquharson** [comment]
[https://xkcd.com/224/](https://xkcd.com/224/)
[https://xkcd.com/297/](https://xkcd.com/297/)

**Comment by bengangllipson** [comment]
"First you gotta set the cooder, and then bang." - My CS Professor in college while talking about the following line of lisp

    (set-cdr! x 4)
